// Generated by tools/generate_cbor_bindings.py; edit src/proto.rs instead.
package infernal_cbor

Monster :: struct {
    format_version: u32,
    id: string,
    display_name: string,
    generation: Maybe(GenerationInfo),
    sprites: Maybe(SpriteSet),
    physics: Maybe(PhysicsInfo),
    gameplay: Maybe(GameplayInfo),
    animations: []Animation,
    attacks: []Attack,
    colliders: []Collider,
    movement_modes: []MovementMode,
    tags: []string,
    description: string,
    behavior: Maybe(BehaviorInfo),
    projectiles: []Projectile,
    size: Maybe(SizeInfo),
    mount: Maybe(MountInfo),
}

MountInfo :: struct {
    rider_package: string,
    mount_package: string,
    survivor: string,
}

SpawnInfo :: struct {
    package_path: string,
    monster_id: string,
    count: u32,
    max_active: u32,
}

SizeInfo :: struct {
    normalized_size: f32,
    size_class: string,
    morphology_scale: f32,
    pixels_per_unit: f32,
    visible_width_px: u32,
    visible_height_px: u32,
    anchor_x_px: f32,
    anchor_y_px: f32,
}

BehaviorInfo :: struct {
    style: string,
    aggro_range: f32,
    preferred_range: f32,
    aggression: f32,
    retreat_health_fraction: f32,
    approach_mode: string,
    escape_mode: string,
    attack_preferences: []AttackPreference,
}

AttackPreference :: struct {
    attack_id: string,
    weight: f32,
}

GenerationInfo :: struct {
    generator_version: string,
    recipe_version: string,
    prompt: string,
    seed: u64,
    parser: string,
    parser_confidence: f32,
    repairs: []string,
    recipe_ids: []string,
    confidences: []SemanticConfidence,
    token_evidence: []TokenEvidence,
}

SemanticConfidence :: struct {
    key: string,
    confidence: f32,
}

TokenEvidence :: struct {
    label: string,
    start: u32,
    end: u32,
    confidence: f32,
}

SpriteSet :: struct {
    image_file: string,
    frame_width: u32,
    frame_height: u32,
    columns: u32,
    frame_count: u32,
    palette_size: u32,
    emission_file: string,
    direction_angles_deg: []f32,
    direction_stride: u32,
    render_mode: string,
}

PhysicsInfo :: struct {
    mass: f32,
    gravity_scale: f32,
    speed: f32,
    knockback_scale: f32,
    center_of_mass_x: f32,
    center_of_mass_y: f32,
    side_effects: []string,
}

GameplayInfo :: struct {
    health: u32,
    defense: u32,
    threat: f32,
    health_size_bonus: u32,
    health_armor_bonus: u32,
    health_magic_bonus: u32,
}

Animation :: struct {
    id: string,
    semantic_state: string,
    frames: []AnimationFrame,
    events: []AnimationEvent,
    looped: bool,
    movement_mode: string,
}

AnimationFrame :: struct {
    sprite_frame_id: u32,
    duration_ms: u32,
    root_dx: f32,
    root_dy: f32,
}

AnimationEvent :: struct {
    time_ms: u32,
    kind: string,
    reference_id: string,
}

Attack :: struct {
    id: string,
    delivery: string,
    element: string,
    origin_node: string,
    damage: u32,
    telegraph_ms: u32,
    cooldown_ms: u32,
    range: f32,
    animation_id: string,
    steps: []AttackStep,
    projectile_id: string,
    spawn: Maybe(SpawnInfo),
}

Projectile :: struct {
    id: string,
    kind: string,
    image_file: string,
    frame_width: u32,
    frame_height: u32,
    columns: u32,
    first_frame: u32,
    frame_count: u32,
    frame_duration_ms: u32,
    collision_radius: f32,
    orientation_mode: string,
}

AttackStep :: struct {
    primitive: string,
    at_ms: u32,
    value: f32,
    target: string,
    count: u32,
    spread_deg: f32,
    speed: f32,
    radius: f32,
    duration_ms: u32,
}

Collider :: struct {
    id: string,
    node_id: string,
    x: f32,
    y: f32,
    radius: f32,
    hurtbox: bool,
    views: []ColliderView,
}

ColliderView :: struct {
    direction_index: u32,
    x: f32,
    y: f32,
    radius: f32,
}

MovementMode :: struct {
    id: string,
    speed: f32,
    animation_id: string,
    category: string,
    modifiers: []string,
}
