// Code generated by tools/generate_cbor_bindings.py; DO NOT EDIT.
package infernalcbor

type Monster struct {
	FormatVersion uint32          `cbor:"format_version"`
	ID            string          `cbor:"id"`
	DisplayName   string          `cbor:"display_name"`
	Generation    *GenerationInfo `cbor:"generation"`
	Sprites       *SpriteSet      `cbor:"sprites"`
	Physics       *PhysicsInfo    `cbor:"physics"`
	Gameplay      *GameplayInfo   `cbor:"gameplay"`
	Animations    []Animation     `cbor:"animations"`
	Attacks       []Attack        `cbor:"attacks"`
	Colliders     []Collider      `cbor:"colliders"`
	MovementModes []MovementMode  `cbor:"movement_modes"`
	Tags          []string        `cbor:"tags"`
	Description   string          `cbor:"description"`
	Behavior      *BehaviorInfo   `cbor:"behavior"`
	Projectiles   []Projectile    `cbor:"projectiles"`
	Size          *SizeInfo       `cbor:"size"`
	Mount         *MountInfo      `cbor:"mount"`
}

type MountInfo struct {
	RiderPackage string `cbor:"rider_package"`
	MountPackage string `cbor:"mount_package"`
	Survivor     string `cbor:"survivor"`
}

type SpawnInfo struct {
	PackagePath string `cbor:"package_path"`
	MonsterID   string `cbor:"monster_id"`
	Count       uint32 `cbor:"count"`
	MaxActive   uint32 `cbor:"max_active"`
}

type SizeInfo struct {
	NormalizedSize  float32 `cbor:"normalized_size"`
	SizeClass       string  `cbor:"size_class"`
	MorphologyScale float32 `cbor:"morphology_scale"`
	PixelsPerUnit   float32 `cbor:"pixels_per_unit"`
	VisibleWidthPx  uint32  `cbor:"visible_width_px"`
	VisibleHeightPx uint32  `cbor:"visible_height_px"`
	AnchorXPx       float32 `cbor:"anchor_x_px"`
	AnchorYPx       float32 `cbor:"anchor_y_px"`
}

type BehaviorInfo struct {
	Style                 string             `cbor:"style"`
	AggroRange            float32            `cbor:"aggro_range"`
	PreferredRange        float32            `cbor:"preferred_range"`
	Aggression            float32            `cbor:"aggression"`
	RetreatHealthFraction float32            `cbor:"retreat_health_fraction"`
	ApproachMode          string             `cbor:"approach_mode"`
	EscapeMode            string             `cbor:"escape_mode"`
	AttackPreferences     []AttackPreference `cbor:"attack_preferences"`
}

type AttackPreference struct {
	AttackID string  `cbor:"attack_id"`
	Weight   float32 `cbor:"weight"`
}

type GenerationInfo struct {
	GeneratorVersion string               `cbor:"generator_version"`
	RecipeVersion    string               `cbor:"recipe_version"`
	Prompt           string               `cbor:"prompt"`
	Seed             uint64               `cbor:"seed"`
	Parser           string               `cbor:"parser"`
	ParserConfidence float32              `cbor:"parser_confidence"`
	Repairs          []string             `cbor:"repairs"`
	RecipeIds        []string             `cbor:"recipe_ids"`
	Confidences      []SemanticConfidence `cbor:"confidences"`
	TokenEvidence    []TokenEvidence      `cbor:"token_evidence"`
}

type SemanticConfidence struct {
	Key        string  `cbor:"key"`
	Confidence float32 `cbor:"confidence"`
}

type TokenEvidence struct {
	Label      string  `cbor:"label"`
	Start      uint32  `cbor:"start"`
	End        uint32  `cbor:"end"`
	Confidence float32 `cbor:"confidence"`
}

type SpriteSet struct {
	ImageFile          string    `cbor:"image_file"`
	FrameWidth         uint32    `cbor:"frame_width"`
	FrameHeight        uint32    `cbor:"frame_height"`
	Columns            uint32    `cbor:"columns"`
	FrameCount         uint32    `cbor:"frame_count"`
	PaletteSize        uint32    `cbor:"palette_size"`
	EmissionFile       string    `cbor:"emission_file"`
	DirectionAnglesDeg []float32 `cbor:"direction_angles_deg"`
	DirectionStride    uint32    `cbor:"direction_stride"`
	RenderMode         string    `cbor:"render_mode"`
}

type PhysicsInfo struct {
	Mass           float32  `cbor:"mass"`
	GravityScale   float32  `cbor:"gravity_scale"`
	Speed          float32  `cbor:"speed"`
	KnockbackScale float32  `cbor:"knockback_scale"`
	CenterOfMassX  float32  `cbor:"center_of_mass_x"`
	CenterOfMassY  float32  `cbor:"center_of_mass_y"`
	SideEffects    []string `cbor:"side_effects"`
}

type GameplayInfo struct {
	Health           uint32  `cbor:"health"`
	Defense          uint32  `cbor:"defense"`
	Threat           float32 `cbor:"threat"`
	HealthSizeBonus  uint32  `cbor:"health_size_bonus"`
	HealthArmorBonus uint32  `cbor:"health_armor_bonus"`
	HealthMagicBonus uint32  `cbor:"health_magic_bonus"`
}

type Animation struct {
	ID            string           `cbor:"id"`
	SemanticState string           `cbor:"semantic_state"`
	Frames        []AnimationFrame `cbor:"frames"`
	Events        []AnimationEvent `cbor:"events"`
	Looped        bool             `cbor:"looped"`
	MovementMode  string           `cbor:"movement_mode"`
}

type AnimationFrame struct {
	SpriteFrameID uint32  `cbor:"sprite_frame_id"`
	DurationMs    uint32  `cbor:"duration_ms"`
	RootDx        float32 `cbor:"root_dx"`
	RootDy        float32 `cbor:"root_dy"`
}

type AnimationEvent struct {
	TimeMs      uint32 `cbor:"time_ms"`
	Kind        string `cbor:"kind"`
	ReferenceID string `cbor:"reference_id"`
}

type Attack struct {
	ID           string       `cbor:"id"`
	Delivery     string       `cbor:"delivery"`
	Element      string       `cbor:"element"`
	OriginNode   string       `cbor:"origin_node"`
	Damage       uint32       `cbor:"damage"`
	TelegraphMs  uint32       `cbor:"telegraph_ms"`
	CooldownMs   uint32       `cbor:"cooldown_ms"`
	Range        float32      `cbor:"range"`
	AnimationID  string       `cbor:"animation_id"`
	Steps        []AttackStep `cbor:"steps"`
	ProjectileID string       `cbor:"projectile_id"`
	Spawn        *SpawnInfo   `cbor:"spawn"`
}

type Projectile struct {
	ID              string  `cbor:"id"`
	Kind            string  `cbor:"kind"`
	ImageFile       string  `cbor:"image_file"`
	FrameWidth      uint32  `cbor:"frame_width"`
	FrameHeight     uint32  `cbor:"frame_height"`
	Columns         uint32  `cbor:"columns"`
	FirstFrame      uint32  `cbor:"first_frame"`
	FrameCount      uint32  `cbor:"frame_count"`
	FrameDurationMs uint32  `cbor:"frame_duration_ms"`
	CollisionRadius float32 `cbor:"collision_radius"`
	OrientationMode string  `cbor:"orientation_mode"`
}

type AttackStep struct {
	Primitive  string  `cbor:"primitive"`
	AtMs       uint32  `cbor:"at_ms"`
	Value      float32 `cbor:"value"`
	Target     string  `cbor:"target"`
	Count      uint32  `cbor:"count"`
	SpreadDeg  float32 `cbor:"spread_deg"`
	Speed      float32 `cbor:"speed"`
	Radius     float32 `cbor:"radius"`
	DurationMs uint32  `cbor:"duration_ms"`
}

type Collider struct {
	ID      string         `cbor:"id"`
	NodeID  string         `cbor:"node_id"`
	X       float32        `cbor:"x"`
	Y       float32        `cbor:"y"`
	Radius  float32        `cbor:"radius"`
	Hurtbox bool           `cbor:"hurtbox"`
	Views   []ColliderView `cbor:"views"`
}

type ColliderView struct {
	DirectionIndex uint32  `cbor:"direction_index"`
	X              float32 `cbor:"x"`
	Y              float32 `cbor:"y"`
	Radius         float32 `cbor:"radius"`
}

type MovementMode struct {
	ID          string   `cbor:"id"`
	Speed       float32  `cbor:"speed"`
	AnimationID string   `cbor:"animation_id"`
	Category    string   `cbor:"category"`
	Modifiers   []string `cbor:"modifiers"`
}
