// Generated by tools/generate_cbor_bindings.py; edit src/proto.rs instead.
using System.Collections.Generic;
using Spotflow.Cbor;

namespace InfernalDiffusion.Cbor;

public sealed class Monster
{
    [CborProperty(TextName = "format_version")]
    public uint FormatVersion { get; set; }
    [CborProperty(TextName = "id")]
    public string ID { get; set; } = "";
    [CborProperty(TextName = "display_name")]
    public string DisplayName { get; set; } = "";
    [CborProperty(TextName = "generation")]
    public GenerationInfo? Generation { get; set; }
    [CborProperty(TextName = "sprites")]
    public SpriteSet? Sprites { get; set; }
    [CborProperty(TextName = "physics")]
    public PhysicsInfo? Physics { get; set; }
    [CborProperty(TextName = "gameplay")]
    public GameplayInfo? Gameplay { get; set; }
    [CborProperty(TextName = "animations")]
    public List<Animation> Animations { get; set; } = new();
    [CborProperty(TextName = "attacks")]
    public List<Attack> Attacks { get; set; } = new();
    [CborProperty(TextName = "colliders")]
    public List<Collider> Colliders { get; set; } = new();
    [CborProperty(TextName = "movement_modes")]
    public List<MovementMode> MovementModes { get; set; } = new();
    [CborProperty(TextName = "tags")]
    public List<string> Tags { get; set; } = new();
    [CborProperty(TextName = "description")]
    public string Description { get; set; } = "";
    [CborProperty(TextName = "behavior")]
    public BehaviorInfo? Behavior { get; set; }
    [CborProperty(TextName = "projectiles")]
    public List<Projectile> Projectiles { get; set; } = new();
    [CborProperty(TextName = "size")]
    public SizeInfo? Size { get; set; }
    [CborProperty(TextName = "mount")]
    public MountInfo? Mount { get; set; }
}

public sealed class MountInfo
{
    [CborProperty(TextName = "rider_package")]
    public string RiderPackage { get; set; } = "";
    [CborProperty(TextName = "mount_package")]
    public string MountPackage { get; set; } = "";
    [CborProperty(TextName = "survivor")]
    public string Survivor { get; set; } = "";
}

public sealed class SpawnInfo
{
    [CborProperty(TextName = "package_path")]
    public string PackagePath { get; set; } = "";
    [CborProperty(TextName = "monster_id")]
    public string MonsterID { get; set; } = "";
    [CborProperty(TextName = "count")]
    public uint Count { get; set; }
    [CborProperty(TextName = "max_active")]
    public uint MaxActive { get; set; }
}

public sealed class SizeInfo
{
    [CborProperty(TextName = "normalized_size")]
    public float NormalizedSize { get; set; }
    [CborProperty(TextName = "size_class")]
    public string SizeClass { get; set; } = "";
    [CborProperty(TextName = "morphology_scale")]
    public float MorphologyScale { get; set; }
    [CborProperty(TextName = "pixels_per_unit")]
    public float PixelsPerUnit { get; set; }
    [CborProperty(TextName = "visible_width_px")]
    public uint VisibleWidthPx { get; set; }
    [CborProperty(TextName = "visible_height_px")]
    public uint VisibleHeightPx { get; set; }
    [CborProperty(TextName = "anchor_x_px")]
    public float AnchorXPx { get; set; }
    [CborProperty(TextName = "anchor_y_px")]
    public float AnchorYPx { get; set; }
}

public sealed class BehaviorInfo
{
    [CborProperty(TextName = "style")]
    public string Style { get; set; } = "";
    [CborProperty(TextName = "aggro_range")]
    public float AggroRange { get; set; }
    [CborProperty(TextName = "preferred_range")]
    public float PreferredRange { get; set; }
    [CborProperty(TextName = "aggression")]
    public float Aggression { get; set; }
    [CborProperty(TextName = "retreat_health_fraction")]
    public float RetreatHealthFraction { get; set; }
    [CborProperty(TextName = "approach_mode")]
    public string ApproachMode { get; set; } = "";
    [CborProperty(TextName = "escape_mode")]
    public string EscapeMode { get; set; } = "";
    [CborProperty(TextName = "attack_preferences")]
    public List<AttackPreference> AttackPreferences { get; set; } = new();
}

public sealed class AttackPreference
{
    [CborProperty(TextName = "attack_id")]
    public string AttackID { get; set; } = "";
    [CborProperty(TextName = "weight")]
    public float Weight { get; set; }
}

public sealed class GenerationInfo
{
    [CborProperty(TextName = "generator_version")]
    public string GeneratorVersion { get; set; } = "";
    [CborProperty(TextName = "recipe_version")]
    public string RecipeVersion { get; set; } = "";
    [CborProperty(TextName = "prompt")]
    public string Prompt { get; set; } = "";
    [CborProperty(TextName = "seed")]
    public ulong Seed { get; set; }
    [CborProperty(TextName = "parser")]
    public string Parser { get; set; } = "";
    [CborProperty(TextName = "parser_confidence")]
    public float ParserConfidence { get; set; }
    [CborProperty(TextName = "repairs")]
    public List<string> Repairs { get; set; } = new();
    [CborProperty(TextName = "recipe_ids")]
    public List<string> RecipeIds { get; set; } = new();
    [CborProperty(TextName = "confidences")]
    public List<SemanticConfidence> Confidences { get; set; } = new();
    [CborProperty(TextName = "token_evidence")]
    public List<TokenEvidence> TokenEvidence { get; set; } = new();
}

public sealed class SemanticConfidence
{
    [CborProperty(TextName = "key")]
    public string Key { get; set; } = "";
    [CborProperty(TextName = "confidence")]
    public float Confidence { get; set; }
}

public sealed class TokenEvidence
{
    [CborProperty(TextName = "label")]
    public string Label { get; set; } = "";
    [CborProperty(TextName = "start")]
    public uint Start { get; set; }
    [CborProperty(TextName = "end")]
    public uint End { get; set; }
    [CborProperty(TextName = "confidence")]
    public float Confidence { get; set; }
}

public sealed class SpriteSet
{
    [CborProperty(TextName = "image_file")]
    public string ImageFile { get; set; } = "";
    [CborProperty(TextName = "frame_width")]
    public uint FrameWidth { get; set; }
    [CborProperty(TextName = "frame_height")]
    public uint FrameHeight { get; set; }
    [CborProperty(TextName = "columns")]
    public uint Columns { get; set; }
    [CborProperty(TextName = "frame_count")]
    public uint FrameCount { get; set; }
    [CborProperty(TextName = "palette_size")]
    public uint PaletteSize { get; set; }
    [CborProperty(TextName = "emission_file")]
    public string EmissionFile { get; set; } = "";
    [CborProperty(TextName = "direction_angles_deg")]
    public List<float> DirectionAnglesDeg { get; set; } = new();
    [CborProperty(TextName = "direction_stride")]
    public uint DirectionStride { get; set; }
    [CborProperty(TextName = "render_mode")]
    public string RenderMode { get; set; } = "";
}

public sealed class PhysicsInfo
{
    [CborProperty(TextName = "mass")]
    public float Mass { get; set; }
    [CborProperty(TextName = "gravity_scale")]
    public float GravityScale { get; set; }
    [CborProperty(TextName = "speed")]
    public float Speed { get; set; }
    [CborProperty(TextName = "knockback_scale")]
    public float KnockbackScale { get; set; }
    [CborProperty(TextName = "center_of_mass_x")]
    public float CenterOfMassX { get; set; }
    [CborProperty(TextName = "center_of_mass_y")]
    public float CenterOfMassY { get; set; }
    [CborProperty(TextName = "side_effects")]
    public List<string> SideEffects { get; set; } = new();
}

public sealed class GameplayInfo
{
    [CborProperty(TextName = "health")]
    public uint Health { get; set; }
    [CborProperty(TextName = "defense")]
    public uint Defense { get; set; }
    [CborProperty(TextName = "threat")]
    public float Threat { get; set; }
    [CborProperty(TextName = "health_size_bonus")]
    public uint HealthSizeBonus { get; set; }
    [CborProperty(TextName = "health_armor_bonus")]
    public uint HealthArmorBonus { get; set; }
    [CborProperty(TextName = "health_magic_bonus")]
    public uint HealthMagicBonus { get; set; }
}

public sealed class Animation
{
    [CborProperty(TextName = "id")]
    public string ID { get; set; } = "";
    [CborProperty(TextName = "semantic_state")]
    public string SemanticState { get; set; } = "";
    [CborProperty(TextName = "frames")]
    public List<AnimationFrame> Frames { get; set; } = new();
    [CborProperty(TextName = "events")]
    public List<AnimationEvent> Events { get; set; } = new();
    [CborProperty(TextName = "looped")]
    public bool Looped { get; set; }
    [CborProperty(TextName = "movement_mode")]
    public string MovementMode { get; set; } = "";
}

public sealed class AnimationFrame
{
    [CborProperty(TextName = "sprite_frame_id")]
    public uint SpriteFrameID { get; set; }
    [CborProperty(TextName = "duration_ms")]
    public uint DurationMs { get; set; }
    [CborProperty(TextName = "root_dx")]
    public float RootDx { get; set; }
    [CborProperty(TextName = "root_dy")]
    public float RootDy { get; set; }
}

public sealed class AnimationEvent
{
    [CborProperty(TextName = "time_ms")]
    public uint TimeMs { get; set; }
    [CborProperty(TextName = "kind")]
    public string Kind { get; set; } = "";
    [CborProperty(TextName = "reference_id")]
    public string ReferenceID { get; set; } = "";
}

public sealed class Attack
{
    [CborProperty(TextName = "id")]
    public string ID { get; set; } = "";
    [CborProperty(TextName = "delivery")]
    public string Delivery { get; set; } = "";
    [CborProperty(TextName = "element")]
    public string Element { get; set; } = "";
    [CborProperty(TextName = "origin_node")]
    public string OriginNode { get; set; } = "";
    [CborProperty(TextName = "damage")]
    public uint Damage { get; set; }
    [CborProperty(TextName = "telegraph_ms")]
    public uint TelegraphMs { get; set; }
    [CborProperty(TextName = "cooldown_ms")]
    public uint CooldownMs { get; set; }
    [CborProperty(TextName = "range")]
    public float Range { get; set; }
    [CborProperty(TextName = "animation_id")]
    public string AnimationID { get; set; } = "";
    [CborProperty(TextName = "steps")]
    public List<AttackStep> Steps { get; set; } = new();
    [CborProperty(TextName = "projectile_id")]
    public string ProjectileID { get; set; } = "";
    [CborProperty(TextName = "spawn")]
    public SpawnInfo? Spawn { get; set; }
}

public sealed class Projectile
{
    [CborProperty(TextName = "id")]
    public string ID { get; set; } = "";
    [CborProperty(TextName = "kind")]
    public string Kind { get; set; } = "";
    [CborProperty(TextName = "image_file")]
    public string ImageFile { get; set; } = "";
    [CborProperty(TextName = "frame_width")]
    public uint FrameWidth { get; set; }
    [CborProperty(TextName = "frame_height")]
    public uint FrameHeight { get; set; }
    [CborProperty(TextName = "columns")]
    public uint Columns { get; set; }
    [CborProperty(TextName = "first_frame")]
    public uint FirstFrame { get; set; }
    [CborProperty(TextName = "frame_count")]
    public uint FrameCount { get; set; }
    [CborProperty(TextName = "frame_duration_ms")]
    public uint FrameDurationMs { get; set; }
    [CborProperty(TextName = "collision_radius")]
    public float CollisionRadius { get; set; }
    [CborProperty(TextName = "orientation_mode")]
    public string OrientationMode { get; set; } = "";
}

public sealed class AttackStep
{
    [CborProperty(TextName = "primitive")]
    public string Primitive { get; set; } = "";
    [CborProperty(TextName = "at_ms")]
    public uint AtMs { get; set; }
    [CborProperty(TextName = "value")]
    public float Value { get; set; }
    [CborProperty(TextName = "target")]
    public string Target { get; set; } = "";
    [CborProperty(TextName = "count")]
    public uint Count { get; set; }
    [CborProperty(TextName = "spread_deg")]
    public float SpreadDeg { get; set; }
    [CborProperty(TextName = "speed")]
    public float Speed { get; set; }
    [CborProperty(TextName = "radius")]
    public float Radius { get; set; }
    [CborProperty(TextName = "duration_ms")]
    public uint DurationMs { get; set; }
}

public sealed class Collider
{
    [CborProperty(TextName = "id")]
    public string ID { get; set; } = "";
    [CborProperty(TextName = "node_id")]
    public string NodeID { get; set; } = "";
    [CborProperty(TextName = "x")]
    public float X { get; set; }
    [CborProperty(TextName = "y")]
    public float Y { get; set; }
    [CborProperty(TextName = "radius")]
    public float Radius { get; set; }
    [CborProperty(TextName = "hurtbox")]
    public bool Hurtbox { get; set; }
    [CborProperty(TextName = "views")]
    public List<ColliderView> Views { get; set; } = new();
}

public sealed class ColliderView
{
    [CborProperty(TextName = "direction_index")]
    public uint DirectionIndex { get; set; }
    [CborProperty(TextName = "x")]
    public float X { get; set; }
    [CborProperty(TextName = "y")]
    public float Y { get; set; }
    [CborProperty(TextName = "radius")]
    public float Radius { get; set; }
}

public sealed class MovementMode
{
    [CborProperty(TextName = "id")]
    public string ID { get; set; } = "";
    [CborProperty(TextName = "speed")]
    public float Speed { get; set; }
    [CborProperty(TextName = "animation_id")]
    public string AnimationID { get; set; } = "";
}
