// Generated by tools/generate_cbor_bindings.py; edit src/proto.rs instead.
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Monster {
    pub format_version: u32,
    pub id: String,
    pub display_name: String,
    pub generation: Option<GenerationInfo>,
    pub sprites: Option<SpriteSet>,
    pub physics: Option<PhysicsInfo>,
    pub gameplay: Option<GameplayInfo>,
    pub animations: Vec<Animation>,
    pub attacks: Vec<Attack>,
    pub colliders: Vec<Collider>,
    pub movement_modes: Vec<MovementMode>,
    pub tags: Vec<String>,
    pub description: String,
    pub behavior: Option<BehaviorInfo>,
    pub projectiles: Vec<Projectile>,
    pub size: Option<SizeInfo>,
    pub mount: Option<MountInfo>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MountInfo {
    pub rider_package: String,
    pub mount_package: String,
    pub survivor: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SpawnInfo {
    pub package_path: String,
    pub monster_id: String,
    pub count: u32,
    pub max_active: u32,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SizeInfo {
    pub normalized_size: f32,
    pub size_class: String,
    pub morphology_scale: f32,
    pub pixels_per_unit: f32,
    pub visible_width_px: u32,
    pub visible_height_px: u32,
    pub anchor_x_px: f32,
    pub anchor_y_px: f32,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct BehaviorInfo {
    pub style: String,
    pub aggro_range: f32,
    pub preferred_range: f32,
    pub aggression: f32,
    pub retreat_health_fraction: f32,
    pub approach_mode: String,
    pub escape_mode: String,
    pub attack_preferences: Vec<AttackPreference>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AttackPreference {
    pub attack_id: String,
    pub weight: f32,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct GenerationInfo {
    pub generator_version: String,
    pub recipe_version: String,
    pub prompt: String,
    pub seed: u64,
    pub parser: String,
    pub parser_confidence: f32,
    pub repairs: Vec<String>,
    pub recipe_ids: Vec<String>,
    pub confidences: Vec<SemanticConfidence>,
    pub token_evidence: Vec<TokenEvidence>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SemanticConfidence {
    pub key: String,
    pub confidence: f32,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TokenEvidence {
    pub label: String,
    pub start: u32,
    pub end: u32,
    pub confidence: f32,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SpriteSet {
    pub image_file: String,
    pub frame_width: u32,
    pub frame_height: u32,
    pub columns: u32,
    pub frame_count: u32,
    pub palette_size: u32,
    pub emission_file: String,
    pub direction_angles_deg: Vec<f32>,
    pub direction_stride: u32,
    pub render_mode: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct PhysicsInfo {
    pub mass: f32,
    pub gravity_scale: f32,
    pub speed: f32,
    pub knockback_scale: f32,
    pub center_of_mass_x: f32,
    pub center_of_mass_y: f32,
    pub side_effects: Vec<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct GameplayInfo {
    pub health: u32,
    pub defense: u32,
    pub threat: f32,
    pub health_size_bonus: u32,
    pub health_armor_bonus: u32,
    pub health_magic_bonus: u32,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Animation {
    pub id: String,
    pub semantic_state: String,
    pub frames: Vec<AnimationFrame>,
    pub events: Vec<AnimationEvent>,
    pub looped: bool,
    pub movement_mode: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AnimationFrame {
    pub sprite_frame_id: u32,
    pub duration_ms: u32,
    pub root_dx: f32,
    pub root_dy: f32,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AnimationEvent {
    pub time_ms: u32,
    pub kind: String,
    pub reference_id: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Attack {
    pub id: String,
    pub delivery: String,
    pub element: String,
    pub origin_node: String,
    pub damage: u32,
    pub telegraph_ms: u32,
    pub cooldown_ms: u32,
    pub range: f32,
    pub animation_id: String,
    pub steps: Vec<AttackStep>,
    pub projectile_id: String,
    pub spawn: Option<SpawnInfo>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Projectile {
    pub id: String,
    pub kind: String,
    pub image_file: String,
    pub frame_width: u32,
    pub frame_height: u32,
    pub columns: u32,
    pub first_frame: u32,
    pub frame_count: u32,
    pub frame_duration_ms: u32,
    pub collision_radius: f32,
    pub orientation_mode: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AttackStep {
    pub primitive: String,
    pub at_ms: u32,
    pub value: f32,
    pub target: String,
    pub count: u32,
    pub spread_deg: f32,
    pub speed: f32,
    pub radius: f32,
    pub duration_ms: u32,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Collider {
    pub id: String,
    pub node_id: String,
    pub x: f32,
    pub y: f32,
    pub radius: f32,
    pub hurtbox: bool,
    pub views: Vec<ColliderView>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ColliderView {
    pub direction_index: u32,
    pub x: f32,
    pub y: f32,
    pub radius: f32,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MovementMode {
    pub id: String,
    pub speed: f32,
    pub animation_id: String,
    pub category: String,
    pub modifiers: Vec<String>,
}
