"""Generate the portable CBOR record types from src/proto.rs.

The generator writes only type declarations. Language-specific decode helpers
live beside them and are maintained by hand.
"""

from pathlib import Path
import re
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "proto.rs"
OUT = ROOT / "bindings" / "cbor"


def schema():
    source = SOURCE.read_text(encoding="utf-8")
    records = []
    for match in re.finditer(r"pub struct (\w+) \{(.*?)\n\}", source, re.S):
        fields = re.findall(r"pub (\w+): ([^,]+),", match.group(2))
        if not fields:
            raise ValueError(f"no fields in {match.group(1)}")
        records.append((match.group(1), fields))
    if not records or records[0][0] != "Monster":
        raise ValueError("could not read canonical Monster schema")
    return records


def pascal(name):
    return "".join("ID" if word == "id" else word.capitalize() for word in name.split("_"))


def wrap_type(rust_type, language):
    scalar = {
        "rust": {"String": "String", "u32": "u32", "u64": "u64", "f32": "f32", "bool": "bool"},
        "go": {"String": "string", "u32": "uint32", "u64": "uint64", "f32": "float32", "bool": "bool"},
        "odin": {"String": "string", "u32": "u32", "u64": "u64", "f32": "f32", "bool": "bool"},
        "csharp": {"String": "string", "u32": "uint", "u64": "ulong", "f32": "float", "bool": "bool"},
    }[language]
    if rust_type.startswith("Option<"):
        inner = wrap_type(rust_type[7:-1], language)
        return {"rust": f"Option<{inner}>", "go": f"*{inner}", "odin": f"Maybe({inner})", "csharp": f"{inner}?"}[language]
    if rust_type.startswith("Vec<"):
        inner = wrap_type(rust_type[4:-1], language)
        return {"rust": f"Vec<{inner}>", "go": f"[]{inner}", "odin": f"[]{inner}", "csharp": f"List<{inner}>"}[language]
    return scalar.get(rust_type, rust_type)


def emit_rust(records):
    lines = [
        "// Generated by tools/generate_cbor_bindings.py; edit src/proto.rs instead.",
        "use serde::{Deserialize, Serialize};", "",
    ]
    for name, fields in records:
        lines += ["#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]", "#[serde(default)]", f"pub struct {name} {{"]
        lines += [f"    pub {field}: {wrap_type(kind, 'rust')}," for field, kind in fields]
        lines += ["}", ""]
    (OUT / "rust" / "src" / "models.rs").write_text("\n".join(lines), encoding="utf-8")


def emit_go(records):
    lines = ["// Code generated by tools/generate_cbor_bindings.py; DO NOT EDIT.", "package infernalcbor", ""]
    for name, fields in records:
        lines.append(f"type {name} struct {{")
        lines += [f'    {pascal(field)} {wrap_type(kind, "go")} `cbor:"{field}"`' for field, kind in fields]
        lines += ["}", ""]
    path = OUT / "go" / "models.go"
    path.write_text("\n".join(lines), encoding="utf-8")
    if gofmt := shutil.which("gofmt"):
        subprocess.run([gofmt, "-w", str(path)], check=True)


def emit_odin(records):
    lines = ["// Generated by tools/generate_cbor_bindings.py; edit src/proto.rs instead.", "package infernal_cbor", ""]
    for name, fields in records:
        lines.append(f"{name} :: struct {{")
        lines += [f"    {field}: {wrap_type(kind, 'odin')}," for field, kind in fields]
        lines += ["}", ""]
    (OUT / "odin" / "models.odin").write_text("\n".join(lines), encoding="utf-8")


def emit_csharp(records):
    lines = [
        "// Generated by tools/generate_cbor_bindings.py; edit src/proto.rs instead.",
        "using System.Collections.Generic;", "using Spotflow.Cbor;", "",
        "namespace InfernalDiffusion.Cbor;", "",
    ]
    for name, fields in records:
        lines.append(f"public sealed class {name}")
        lines.append("{")
        for field, kind in fields:
            mapped = wrap_type(kind, "csharp")
            initial = " = new();" if mapped.startswith("List<") else ' = "";' if mapped == "string" else ""
            lines.append(f'    [CborProperty(TextName = "{field}")]')
            lines.append(f"    public {mapped} {pascal(field)} {{ get; set; }}{initial}")
        lines += ["}", ""]
    (OUT / "csharp" / "Models.cs").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    records = schema()
    for path in (OUT / "rust" / "src", OUT / "go", OUT / "odin", OUT / "csharp"):
        path.mkdir(parents=True, exist_ok=True)
    emit_rust(records)
    emit_go(records)
    emit_odin(records)
    emit_csharp(records)
    print(f"Generated {len(records)} CBOR record types for four languages")
